### ISSUE TITLE
"Cannot find module" after upgrading from 0.8.1 to 1.0.1

### ISSUE THREAD

**Issue by Leonya** [Anber/wyw-in-js#217]
Getting the following exception after upgrading:

```
10:12:25 AM [vite] Internal server error: Cannot find module '@/components/Flex.ts'
Require stack:
- /Users/leonidkhachaturov/code/space/darkmatter-web/src/components/Centered/Centered.ts in/Users/leonidkhachaturov/code/space/darkmatter-web/src/components/Centered/Centered.ts

  Plugin: wyw-in-js
  File: /Users/leonidkhachaturov/code/space/darkmatter-web/src/components/Centered/Centered.ts
      at Module.evaluate (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/module.js:268:13)
      at evaluate (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/evaluators/index.js:14:5)
      at BaseAction.evalFile [as handler] (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/generators/evalFile.js:35:43)
      at evalFile.next (<anonymous>)
      at /Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:71:78
      at EventEmitter.action (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/utils/EventEmitter.js:25:22)
      at BaseAction.emitAction (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:136:39)
      at nextFn (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:71:32)
      at processNext (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:116:28)
      at Object.next (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/BaseAction.js:125:9)
      at asyncActionRunner (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:39:102)
      at asyncActionRunner (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform/actions/actionRunner.js:46:28)
      at async transform (/Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/transform/lib/transform.js:118:20)
      at async TransformPluginContext.transform (file:///Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/@wyw-in-js/vite/esm/index.mjs:372:22)
      at async EnvironmentPluginContainer.transform (file:///Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/vite/dist/node/chunks/node.js:31351:14)
      at async loadAndTransform (file:///Users/leonidkhachaturov/code/space/darkmatter-web/node_modules/vite/dist/node/chunks/node.js:26319:26)
```

`@` is an alias defined in vite.config.js:

```
"@": path.resolve(__dirname, "./src")
```

I have tried both Vite 8 beta and Vite 7.3.1, both don't work.

**Comment by Leonya** [comment]
[darkmatter-web-repro.zip](https://github.com/user-attachments/files/24559989/darkmatter-web-repro.zip)

There you go, hope it helps.

**Comment by Anber** [comment]
```
- createAsyncResolver(this.resolve)
+ createAsyncResolver(this.resolve.bind(this))
```

Faceplam.jpg. I will publish 1.0.4 a bit later today.
